#Austin Schenk
#Project Euler 
#Problem 2

"Problem 2:
Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose 
values do not exceed four million, find the sum of the 
even-valued terms."



leo = function(n){
  fibs <- vector()
  fibs[1] = 1
  fibs[2] = 1
  
  for (i in 3:n){
    fibs[i] = fibs[i-1] + fibs[i-2]
  }
  sumfibs <- (sum(fibs[fibs %% 2 == 0]))
  list(fibs, sumfibs)
  
}

leo(10)
leo(100) #massive 
leo(50)
leo(25)
leo(40)
leo(35)
leo(33) #bingo 




